name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Build and push Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --platform linux/arm/v7 --tag ${{secrets.DOCKER_USER}}/personal-manga-reader:$GITHUB_SHA --push
        docker build . --platform linux/arm/v7 --tag ${{secrets.DOCKER_USER}}/personal-manga-reader:latest --push
        echo "Docker push successfully"
        echo ${{secrets.DOCKER_USER}}/personal-manga-reader:$GITHUB_SHA
