name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/app_image
    - name: Docker Push
      run: |
        docker tag app_image ${{secrets.DOCKER_USER}}/personal-manga-reader:$GITHUB_SHA
        docker push ${{secrets.DOCKER_USER}}/personal-manga-reader:$GITHUB_SHA
        docker tag app_image ${{secrets.DOCKER_USER}}/personal-manga-reader:latest
        docker push ${{secrets.DOCKER_USER}}/personal-manga-reader:latest
